PrMngSystem/Models/Task.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrMngSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        [Browsable(false)]
        public int taskID { get; set; }
        [Display(Name = "Project ID")]
        public int projectID { get; set; }
        [Display(Name = "Progress %")]
        public Nullable<decimal> progress { get; set; }
        [Display(Name = "Deadline")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime deadline { get; set; }
        [Display(Name = "Description")]
        public string description { get; set; }
        [Display(Name = "Status")]
        public int status { get; set; }
        [Display(Name = "Assignee")]
        public Nullable<int> assignee { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual User User { get; set; }
    }
}

PrMngSystem/Controllers/ProjectController.cs
using PrMngSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrMngSystem.Controllers
{
    public class ProjectController : Controller
    {
        private PrMngSystemDBEntities db = new PrMngSystemDBEntities();

        [Authorize]
        public ActionResult Projects()
        {
            var userInfo = (from r in db.Users
                          where r.username == User.Identity.Name
                          select r).FirstOrDefault();

            //manager see only his projects
            if(userInfo.roleID == 2)
            {
                return View(db.Projects.Where(p => p.manage == userInfo.userID).ToList());
            }

            return View(db.Projects.ToList());
        }

        // GET: Home/Create
        public ActionResult CreateProject()
        {
            //manager can not assign project to someone else
            var roleId = (from r in db.Users
                          where r.username == User.Identity.Name
                          select r.roleID).FirstOrDefault();

            switch (roleId)
            {
                case 1:
                    ViewBag.Manage = true;
                    break;
                case 2:
                    ViewBag.Manage = false;
                    break;
                default:
                    ViewBag.Manage = false;
                    break;
            }

            // Find the users in that role
            var roleUsers = (from p in db.Users

                             where p.roleID == 2

                             select p);

            List<User> ManagerList = roleUsers.ToList();

            ViewBag.Managers = new SelectList(ManagerList, "userID", "username");

            return View();
        }

        // POST: Home/Create
        [HttpPost]
        public ActionResult CreateProject(Project newProject)
        {

            if (!ModelState.IsValid)
                return View(newProject);

            using (PrMngSystemDBEntities db = new PrMngSystemDBEntities())
            {
                var userInfo = db.Users.SingleOrDefault(u => u.username == User.Identity.Name);

                if (userInfo.roleID == 2)
                {
                    newProject.manage = userInfo.userID;
                }
                
                db.Projects.Add(newProject);
                db.SaveChanges();
            }

            return RedirectToAction("Projects");

        }

        // GET: Home/Edit/5
        public ActionResult EditProject(int id)
        {
            var projectUpdate = (from p in db.Projects

                                 where p.projectID == id

                                 select p).FirstOrDefault();

            //manager can not assign project to someone else
            var roleId = (from r in db.Users
                          where r.username == User.Identity.Name
                          select r.roleID).FirstOrDefault();

            switch (roleId)
            {
                case 1:
                    ViewBag.Manage = true;
                    break;
                case 2:
                    ViewBag.Manage = false;
                    break;
                default:
                    ViewBag.Manage = false;
                    break;
            }

            // Find the users in that role
            var roleUsers = (from p in db.Users

                             where p.roleID == 2

                             select p);

            List<User> ManagerList = roleUsers.ToList();

            ViewBag.Managers = new SelectList(ManagerList, "userID", "username");

            return View(projectUpdate);
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult EditProject(Project projectEdit)
        {

            var projectUpdate = db.Projects.SingleOrDefault(p => p.projectID == projectEdit.projectID);

            if (!ModelState.IsValid)

                return View(projectEdit);

            if (projectUpdate != null)
            {
                var userInfo = db.Users.SingleOrDefault(u => u.username == User.Identity.Name);

                projectUpdate.project_code = projectEdit.project_code;
                projectUpdate.project_name = projectEdit.project_name;
                if (userInfo.roleID == 2)
                {
                    projectUpdate.manage = userInfo.userID;
                }
                else
                {
                    projectUpdate.manage = projectEdit.manage;
                }

                db.SaveChanges();
            }
                

            return RedirectToAction("Projects");
        }

        // GET: Home/Delete/5
        public ActionResult DeleteProject(int id)
        {
            var projectDelete = (from p in db.Projects

                                 where p.projectID == id

                                 select p).FirstOrDefault();

            return View(projectDelete);
        }


        // POST: Home/Delete/5
        [HttpPost, ActionName("DeleteProject")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!ModelState.IsValid)
                return View();

            using (PrMngSystemDBEntities db = new PrMngSystemDBEntities())
            {
                var projectDelete = db.Projects.Where(p => p.projectID == id).FirstOrDefault();

                //delete all tasks of project
                var listTasks = projectDelete.Tasks.ToList();
                listTasks.ForEach(x => db.Tasks.Remove(x));

                //delete project
                db.Projects.Remove(projectDelete);

                db.SaveChanges();
            }

            return RedirectToAction("Projects");

        }


    }
}

PrMngSystem/Controllers/TaskController.cs
using PrMngSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrMngSystem.Controllers
{
    public class TaskController : Controller
    {
        private PrMngSystemDBEntities db = new PrMngSystemDBEntities();
        

        // GET: Task
        [Authorize]
        public ActionResult Tasks()
        {
            // Look up the role, show task depending on role
            var userInfo = (from r in db.Users
                            where r.username == User.Identity.Name
                            select r).FirstOrDefault();

            if (userInfo == null)
            {
                return RedirectToAction("Login", "User");
            }

            List<object> AssigneeList = getAssigneeDev();
            ViewBag.Assignee = new SelectList(AssigneeList, "userID", "username");

            switch (userInfo.roleID)
            {
                case 1:
                    ViewBag.ReadonlyDate = false;
                    ViewBag.ReadonlyAssignee = false;
                    break;
                case 2:
                    ViewBag.ReadonlyDate = true;
                    ViewBag.ReadonlyAssignee = false;
                    break;
                default:
                    ViewBag.ReadonlyDate = true;
                    ViewBag.ReadonlyAssignee = true;
                    break;
            }

            if (userInfo == null)
            {
                return RedirectToAction("Login", "User");
            }

            ViewBag.RoleID = userInfo.roleID;

            switch (userInfo.roleID)
            {
                case 2:
                  var result =  from t in db.Tasks
                                join p in db.Projects on t.projectID equals p.projectID
                                where p.manage == userInfo.userID
                                select t;

                    return View(result.ToList());
                case 3:
                    var countAssignTasks = db.Tasks.Where(t => t.assignee == userInfo.userID).Count();

                    if (countAssignTasks > 2)
                    {
                        return View(db.Tasks.Where(t => t.assignee == userInfo.userID).ToList());
                    }
                    else
                    {
                        return View(db.Tasks.Where(t => t.assignee == userInfo.userID || t.assignee == null).ToList());
                    }
                default:
                    return View(db.Tasks.ToList());
            }
        }

        // GET: Task/TasksProject/1
        public ActionResult TasksProject(int id)
        {

            // Look up the role, show task depending on role
            var userInfo = (from r in db.Users
                            where r.username == User.Identity.Name
                            select r).FirstOrDefault();

            if (userInfo == null)
            {
                return RedirectToAction("Login", "User");
            }

            List<object> AssigneeList = getAssigneeDev();
            ViewBag.Assignee = new SelectList(AssigneeList, "userID", "username");

            switch (userInfo.roleID)
            {
                case 1:
                    ViewBag.ReadonlyDate = false;
                    ViewBag.ReadonlyAssignee = false;
                    break;
                case 2:
                    ViewBag.ReadonlyDate = true;
                    ViewBag.ReadonlyAssignee = false;
                    break;
                default:
                    ViewBag.ReadonlyDate = true;
                    ViewBag.ReadonlyAssignee = true;
                    break;
            }

            ViewBag.RoleID = userInfo.roleID;

            var project = (from p in db.Projects

                           where p.projectID == id

                           select p).First();
        
            return View(project.Tasks.ToList());

        }

        // GET: Task/CreateTask
        public ActionResult CreateTask()
        {
            List<object> AssigneeList = getAssigneeDev();
            ViewBag.Assignee = new SelectList(AssigneeList, "userID", "username");

            List<ProjectStatu> StatusList = db.ProjectStatus.ToList();
            ViewBag.Status = new SelectList(StatusList, "statusID", "status_desc");

            return View();
        }

        // POST: Task/CreateTask/1
        [HttpPost]
        public ActionResult CreateTask(int id, Task newTask)
        {

            if (!ModelState.IsValid)
                return View(newTask);

            using (PrMngSystemDBEntities db = new PrMngSystemDBEntities())
            {
                newTask.projectID = id;

                db.Tasks.Add(newTask);
                db.SaveChanges();

                var project = db.Projects.Find(id);

                project.Tasks.Add(newTask);
            }

            UpdateProjectProgress(newTask, "create");

            return RedirectToAction("Tasks");

        }

        // GET: Task/EditTask/5
        public ActionResult EditTask(int id)
        {
            var tasktUpdate = (from t in db.Tasks

                               where t.taskID == id

                               select t).FirstOrDefault();

            var roleId = (from r in db.Users
                          where r.username == User.Identity.Name
                          select r.roleID).FirstOrDefault();


            List<object> AssigneeList = getAssigneeDev();
            ViewBag.Assignee = new SelectList(AssigneeList, "userID", "username");

            List<ProjectStatu> StatusList = db.ProjectStatus.ToList();
            ViewBag.Status = new SelectList(StatusList, "statusID", "status_desc");

            switch (roleId)
            {
                case 1:
                    ViewBag.ReadonlyDate = false;
                    ViewBag.ReadonlyAssignee = false;
                    break;
                case 2:
                    ViewBag.ReadonlyDate = true;
                    ViewBag.ReadonlyAssignee = false;
                    break;
                default:
                    ViewBag.ReadonlyDate = true;
                    ViewBag.ReadonlyAssignee = true;
                    break;
            }


            return View(tasktUpdate);
        }

        // POST: Task/EditTask/5
        [HttpPost]
        public ActionResult EditTask(Task taskEdit)
        {

            var taskUpdate = db.Tasks.SingleOrDefault(t => t.taskID == taskEdit.taskID);
            var userInfo = (from r in db.Users
                          where r.username == User.Identity.Name
                          select r).FirstOrDefault();

            if (!ModelState.IsValid)

                return View(taskEdit);

            if (taskUpdate != null)
            {
                taskUpdate.progress = taskEdit.progress;
                taskUpdate.deadline = taskEdit.deadline;
                taskUpdate.description = taskEdit.description;
                taskUpdate.status = taskEdit.status;
                if (userInfo.roleID == 3)
                {
                    taskUpdate.assignee = userInfo.userID; 
                }
                else
                {
                    taskUpdate.assignee = taskEdit.assignee;
                }

                db.SaveChanges();

                UpdateProjectProgress(taskEdit, "edit");

            }


            return RedirectToAction("Tasks");
        }

        // GET: Task/DeleteTask/5
        public ActionResult DeleteTask(int id)
        {
            var taskDelete = (from t in db.Tasks

                              where t.taskID == id

                              select t).FirstOrDefault();

            return View(taskDelete);
        }


        // POST: Task/DeleteTask/5
        [HttpPost, ActionName("DeleteTask")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteTaskConfirmed(int id)
        {
            if (!ModelState.IsValid)
                return View();

            using (PrMngSystemDBEntities db = new PrMngSystemDBEntities())
            {

                var taskDelete = db.Tasks.Where(t => t.taskID == id).FirstOrDefault();

                //remove Task from Project list of Tasks
                var project = db.Projects.SingleOrDefault(p => p.projectID == taskDelete.projectID);
                project.Tasks.Remove(taskDelete);

                //delete task
                db.Tasks.Remove(taskDelete);

                db.SaveChanges();

                UpdateProjectProgress(taskDelete, "delete");
            }

            return RedirectToAction("Tasks");

        }

        [HttpPost]
        public ActionResult AssignTask(int id, string assign)
        {
            var taskUpdate = db.Tasks.SingleOrDefault(t => t.taskID == id);
            var taskAssignee = db.Users.SingleOrDefault(t => t.username == assign);

            if (!ModelState.IsValid)

                return View();

            if (taskUpdate != null && taskAssignee != null)
            {
                var countAssignTasks = db.Tasks.Where(t => t.assignee == taskAssignee.userID).Count();

                if (countAssignTasks > 2)
                {
                    return RedirectToAction("Tasks");
                }
            
                taskUpdate.assignee = taskAssignee.userID;

                db.SaveChanges();

            }


            return RedirectToAction("Tasks");
        }

        [HttpPost]
        public ActionResult UnassignTask(int id)
        {

            var taskUpdate = db.Tasks.SingleOrDefault(t => t.taskID == id);

            if (!ModelState.IsValid)

                return View();

            if (taskUpdate != null)
            {
                taskUpdate.assignee = null;

                db.SaveChanges();
            }


            return RedirectToAction("Tasks");
        }

        private List<object> getAssigneeDev()
        {

            var userInfo = (from r in db.Users

PrMngSystem/Views/Task/CreateTask.cshtml
@model PrMngSystem.Models.Task

@{
    ViewBag.Title = "CreateTask";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="jumbotron jumbotron-fluid">
        <h2>New Task</h2>
        <div class="form-horizontal" style="border: groove; border-color: darkseagreen">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
               
            <div class="form-group">
                @Html.LabelFor(model => model.progress, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.progress, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.progress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.deadline, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.deadline, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.deadline, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.status, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.status, ViewBag.Status as SelectList,
            "Select Status", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.assignee, "Assign to", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.assignee, ViewBag.Assignee as SelectList,
            "Select Developer", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.assignee, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create task" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-danger">
        @ViewBag.Message
    </div>
}

<div>
    @Html.ActionLink("Back to Tasks List", "Tasks")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <style>
        h2 {
            background-color: darkseagreen;
            color: white
        }
    </style>
}

PrMngSystem/Views/Task/TasksProject.cshtml
@model IEnumerable<PrMngSystem.Models.Task>

@{
    ViewBag.Title = "Tasks";
}
@*<p>

        @Html.ActionLink("Create New Task", "CreateTask", new { id = Model})
    </p>*@
<div class="jumbotron jumbotron-fluid">
    <h2>Tasks</h2>
    <div class="wrapper">
        <div id="overlay">
            <table height=100% width=100%>
                <tr>
                    <td align=center>
                        <h1>Please wait...</h1>
                    </td>
                </tr>
            </table>
        </div>
        <div class="form-wrapper">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Project.project_code)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.description)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.ProjectStatu.status_desc)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.progress)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.deadline)
                        </th>
                        <th scope="col">
                            Assignee
                        </th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Project.project_code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.description)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.ProjectStatu.status_desc)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.progress)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.deadline)
                            </td>
                            <td>
                                @if (item.assignee != null)
                                {
                                    @Html.DisplayFor(modelItem => item.User.username)
                                    <a href="#" class="unassign-link" data-linkid="@Html.Raw(item.taskID)">Unassign</a>
                                }
                                else
                                {
                                    if (ViewBag.RoleID != 3)
                                    {
                                        <a href="#" class="assign-link" data-linkid="@Html.Raw(item.taskID)" id="@("assignLink" + item.taskID)">Assign</a>
                                        <a href="#" class="cancel-link" data-linkid="@Html.Raw(item.taskID)" id="@("cancelLink" + item.taskID)" style="display: none;">Cancel</a>

                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <div class="drpAssignee" id="@("drpAssignee" + item.taskID)" style="display: none;">
                                                    @Html.DropDownListFor(modelItem => item.assignee, ViewBag.Assignee as SelectList,
                                                "Select", new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(modelItem => item.assignee, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>
                                    }
                                    else
                                    {
                                        @*@Html.Raw(Html.ActionLink("Assign to me", "AssignTask", "Task", new { id = item.taskID, assign = User.Identity.Name }, null));*@
                                        <a href="#" class="assignToMe-link" data-linkid="@Html.Raw(item.taskID)">Assign to me</a>

                                    }

                                }

                            </td>
                            <td>
                                @Html.ActionLink("Edit", "EditTask", new { id = item.taskID })
                                @if (ViewBag.RoleID == 1)
                                {
                                    @Html.ActionLink("Delete", "DeleteTask", new { id = item.taskID })
                                }
                            </td>
                        </tr>
                    }
                </tbody>
                @if (!ViewBag.ReadonlyAssignee)
            {
                    <div>
                        @Html.ActionLink("Go to Projects List", "Projects", "Project")
                    </div>
                }

                <span class="hidenID" style="display: none;">@User.Identity.Name</span>


            </table>
        </div>

    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $(document).ready(function () {
            var taskID = "";

            $('.assign-link').click(function (e) {

                taskID = $(this).attr("data-linkid");

                var linkID = "assignLink" + taskID;
                var dpID = "drpAssignee" + taskID;
                var cancelID = "cancelLink" + taskID;

                var elements = document.getElementsByClassName("drpAssignee");

                for (var i = 0; i < elements.length; i++) {
                    var elementID = elements[i].id;
                    var id = elementID.substring(11); //get ID after drpAssignee

                    if (elementID != dpID) {
                        elements[i].style.display = "none";
                        document.getElementById("assignLink" + id).style.display = "block";
                        document.getElementById("cancelLink" + id).style.display = "none";
                    } else {
                        elements[i].style.display = "block";
                        document.getElementById(linkID).style.display = "none";
                        document.getElementById(cancelID).style.display = "block";
                    }

                }

            });

            $('.cancel-link').click(function (e) {

                var linkID = "assignLink" + taskID;
                var dpID = "drpAssignee" + taskID;
                var cancelID = "cancelLink" + taskID;
                document.getElementById(dpID).style.display = "none";
                document.getElementById(linkID).style.display = "block";
                document.getElementById(cancelID).style.display = "none";
            });

            $('.drpAssignee').change(function (evt) {

                document.getElementById('overlay').style.display = 'block';

                var username = $('#drpAssignee' + taskID + ' :selected').text();

                if (username != "Select") {

                    $.ajax({
                        url: "/Task/AssignTask",
                        type: 'POST',
                        data: { id: taskID, assign: username },
                        success: function (response) {
                            document.getElementById('overlay').style.display = 'none';
                            location.reload();
                        },
                        error: function (xhr) {
                            document.getElementById('overlay').style.display = 'none';
                            alert("Something went wrong, please try again");
                        }
                    });
                }
            });

            $('.assignToMe-link').click(function (e) {

                document.getElementById('overlay').style.display = 'block';

                taskID = $(this).attr("data-linkid");

                username = $('.hidenID').text();

                $.ajax({
                    url: "/Task/AssignTask",
                    type: 'POST',
                    data: { id: taskID, assign: username },
                    success: function (response) {
                        document.getElementById('overlay').style.display = 'none';
                        location.reload();
                    },
                    error: function (error) {
                        document.getElementById('overlay').style.display = 'none';
                        alert("Something went wrong, please try again");
                    }
                });
            });

            $('.unassign-link').click(function (e) {

                document.getElementById('overlay').style.display = 'block';

                var taskID = $(this).attr("data-linkid");

                $.ajax({
                    url: "/Task/UnassignTask",
                    type: 'POST',
                    data: { id: taskID },
                    success: function (response) {
                        document.getElementById('overlay').style.display = 'none';
                        location.reload();
                    },
                    error: function (error) {
                        document.getElementById('overlay').style.display = 'none';
                        alert("Something went wrong, please try again");
                    }
                });
            });

        });


    </script>
    <style type="text/css">
        .wrapper {
            position: relative;
        }

        #overlay {
            position: absolute;
            width: 100%;
            height: 100%;
            z-index: 900;
            background-color: #000;
            opacity: 0.4;
            display: none;
        }
    </style>
}